openapi: '3.0.2'
info:
  title: Bot Pilot
  version: '1.0'
servers:
  - url: https://127.0.0.1
paths:
  /auth/users/:
    post:
      parameters:
        - name: email
          in: query
          description: valid email
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: valid password
          required: true
          schema:
            type: string
        # - name: Authorization
        #   in: header
        #   description: JWT token obtained from the authentication server
        #   required: true
        #   schema:
        #     type: string

      responses:
        '200':
          description: OK
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    description: user email
                  id: 
                    type: number
                    description: user id in db
        '400':
          description: BAD REQUEST
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  email:
                    required: false
                    type: string
                    description: user email
                  password: 
                    required: false
                    type: string
                    description: user id in db

  /auth/jwt/create/:
    post:
      parameters:
        - name: email
          in: query
          description: valid email
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: valid password
          required: true
          schema:
            type: string
        # - name: Authorization
        #   in: header
        #   description: JWT token obtained from the authentication server
        #   required: true
        #   schema:
        #     type: string

      responses:
        '200':
          description: OK
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  refresh:
                    type: string
                    description: jwt refresh token
                  acces: 
                    type: string
                    description: jw acces token
        '400':
          description: BAD REQUEST
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  email:
                    required: false
                    type: string
                    description: user email
                  password: 
                    required: false
                    type: string
                    description: user id in db
  bots/create/:
    post:
      parameters:
        - name: token
          in: query
          description: valid token
          required: true
          schema:
            type: string
        - name: start_message
          in: query
          description: valid password
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Created
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    description: bot id
                  name:
                    type: string
                    description: bot name
                  img:
                    type: string
                    description: bot image
                  token:
                    type: string
                  lang:
                    type: string
                    description: bot language
                  desc:
                    type: string
                    description: bot description
                  date_update:
                    type: string
                    description: create date